# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http = ENV['http_proxy']
    config.proxy.https = ENV['https_proxy']
    config.proxy.no_proxy = ENV['no_proxy'] 
  end

  config.vm.box = "CentOS7"

  config.vm.define "master" do |master|
    master.vm.network :private_network, ip:"192.168.33.14"
  end
  config.vm.define "slave" do |slave|
    slave.vm.network :private_network, ip:"192.168.33.15"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "master" => ["master"],
      "slave" => ["slave"],
      "all" => ["master","slave"]
    }
    ansible.playbook = "ansible/playbook.yaml"
  end


  
end
