# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "CentOS7"
  config.vm.network :private_network, ip:"192.168.33.14"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end

  if Vagrant.has_plugin?("vagrant-proxyconf") and ENV.has_key?("HTTP_PROXY")
    config.proxy.http = ENV["HTTP_PROXY"]
    config.proxy.https = ENV["HTTPS_PROXY"]
    config.proxy.no_proxy = ENV["NO_PROXY"] 
  end
end
